### PR TITLE
Add links to Replicate's mPLUG-Owl demo 

### PR DESCRIPTION
**Pull request by joehoover**
Hi team 👋 ! This PR modifies the mPLUG-Owl README with links to Replicate's mPLUG-Owl [demo](https://replicate.com/joehoover/mplug-owl).

I've added mPLUG-Owl to the [Replicate](https://replicate.com/) platform so that our users and the greater community can experiment with this incredible model! Replicate is a serverless ML platform that lets you run models with a few lines of code. We currently have mPLUG-Owl running on A100s that will scale with demand.

I attempted to maintain the style and format you've already established in your README, but let me know if I need to modify anything! 

We would also love to transfer the model to your group's namespace. If someone would like to create an account, we can handle the transfer of the model to your account. It's free, of course, and your model would be properly associated with your group (e.g. see Whisper [here](https://replicate.com/openai/whisper), for an example)!

### CODE REVIEW

**Comment by MAGAer13** [comment]
Cool. Thanks for contributing the demo link.

**Comment by MAGAer13** [comment]
@joehoover Since we would have a large update on the codebase that support huggingface natively as well as add the support for video input in the next few days. Would you mind supporting it as well once we have release the latest codebase?

**Comment by MAGAer13** [comment]
Also it would be great if adding paper citation information on the demo page as well so others can easily find the paper. Thanks. 😄

**Comment by joehoover** [comment]
Hi @MAGAer13 , awesome, thanks for merging! And I'll be sure to open an issue to update the model in our backlog. 

In the meantime, it'd be great if you could open an account for your team at [replicate](https://replicate.com/). Just pick a username that's associated with your group, I can move the model's ownership to your namespace!

**Pull request merged**
